#!/bin/bash

mypath=`realpath "$0"`
directory=`dirname "$mypath"`
filename=`basename "$directory"`
cd "$directory"

#git config --global user.email "githubfortyuds@gmail.com"
#git remote add $filename https://BRICOMATA8@github.com/BRICOMATA8/$filename.git

git add -v .
git add /home/aghiles/Downloads/bin/ns-3/examples
git commit -m "commit"
git pull -f $filename master
#firefox https://github.com/BRICOMATA8/$filename.git

