#!/bin/bash

mytitle="Server"
echo -e '\033]2;'$mytitle'\007'

projectPath=/home/aghiles/These/Program/C/Contiki/bin/contiki
contikiPath=/home/aghiles/These/Program/C/Contiki/src/contiki-utlc
## Set up the Border Router
#cd $contikiPath/examples/zolertia/project/1-border-router/
#sudo make border-router.upload PORT=/dev/ttyUSB0 TARGET="zoul"


## Setup of Traffic lights
#cd $contikiPath/examples/zolertia/project/2-trafficlight-control
#sudo make trafficlight-control.upload PORT=/dev/ttyUSB1 TARGET="zoul"


## Set up touch sensors
#cd $contikiPath/examples/zolertia/project/3-sensors/
#sudo make touch-sensor.upload PORT=/dev/ttyUSB2 TARGET="zoul"

### USB
#cd $contikiPath/tools/
#sudo ./tunslip6 -s /dev/ttyUSB0 aaaa::1/64

# Final implementation for the project
#cd $contikiPath/examples/zolertia/project/1-border-router/paho-mqtt/
#python UDP-MQTT-final-server.py


# Prepare Ubidots for the reception of data
#cd $contikiPath/examples/zolertia/tutorial/02-ipv6/03-udp-client-and-server/

# Setup of Traffic lights
#cd $contikiPath/examples/zolertia/tutorial/02-ipv6/03-udp-client-and-server/

title1="Connexion"
title3="Server"

cmd1="cd $projectPath/tools/ && make tunslip6 && sudo ./tunslip6 -s /dev/ttyUSB1 aaaa::1/64"
cmd3="cd $contikiPath/1-border-router/paho-mqtt/ && sudo python UDP-MQTT-final-server.py"

gnome-terminal --tab --title="$title1" --command="bash -c '$cmd1; $SHELL'" \
               --tab --title="$title3" --command="bash -c '$cmd3; $SHELL'" 
               

