#!/bin/bash

gnome-terminal --working-directory=Aghiles/Program/C/Contiki/bin/onos -e "sudo tools/build/onos-buck run onos-local -- clean debug"
#cd onos && tools/build/onos-buck run onos-local -- clean debug

