function createaxes(Parent1, X1, YMatrix1)
%CREATEAXES(PARENT1, X1, YMATRIX1)
%  PARENT1:  axes parent
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Jun-2018 15:57:34

% Create axes
axes1 = axes('Parent',Parent1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',1,'Parent',axes1);
set(plot1(1),'DisplayName','Source','Marker','+','Color',[0 0 1]);
set(plot1(2),'DisplayName','Relay','Marker','o','Color',[0 1 0]);
set(plot1(3),'DisplayName','Destination','Marker','x','Color',[1 0 0]);

% Create xlabel
xlabel('Time (s)','LineWidth',20,'FontSize',14);

% Create ylabel
ylabel('Current consumption (A)','LineWidth',20,'FontSize',14);

% Create title
title('Current consumption in direct communication ','LineWidth',20,...
    'FontSize',14);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.03527 0.214]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.01 0.06]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'LineWidth',1);
