#!/bin/bash

mytitle="Sensor"
echo -e '\033]2;'$mytitle'\007'

#contikiPath=/home/aghiles/These/Program/C/Contiki/src/contiki-utlc

## Set up the Border Router
#cd $contikiPath/examples/zolertia/project/1-border-router/
#sudo make border-router.upload PORT=/dev/ttyUSB0 TARGET="zoul"
## USB
#cd $contikiPath/tools/
#./tunslip6 -s /dev/ttyUSB0 aaaa::1/64


## Setup of Traffic lights
#cd $contikiPath/examples/zolertia/project/2-trafficlight-control
#sudo make trafficlight-control.upload PORT=/dev/ttyUSB1 TARGET="zoul"


# Set up touch sensors
cd 3-sensors/
sudo make touch-sensor.upload PORT=/dev/ttyUSB2 TARGET="zoul"

sudo make TARGET=zoul BOARD=firefly PORT=/dev/ttyUSB2 login

## Final implementation for the project
#cd $contikiPath/examples/zolertia/project/1-border-router/paho-mqtt/
#python UDP-MQTT-final-server.py


# Prepare Ubidots for the reception of data
#cd $contikiPath/examples/zolertia/tutorial/02-ipv6/03-udp-client-and-server/

# Setup of Traffic lights
#cd $contikiPath/examples/zolertia/tutorial/02-ipv6/03-udp-client-and-server/

