#!/bin/bash

#sudo mn --topo tree,depth=2,fanout=3 --controller=remotet

gnome-terminal --working-directory=These/Program/C/Contiki/djoudi -e "sudo mn --topo tree,depth=2,fanout=3 --controller=remote,ip=127.0.0.1"

