ACLOCAL_AMFLAGS=-I m4 

lib_LTLIBRARIES = libapplication_epidemic.la

libapplication_epidemic_la_CFLAGS = $(CFLAGS) $(GLIB_FLAGS) $(GSL_FLAGS) -Wall

libapplication_epidemic_la_SOURCES = YOUR_LIBRARY_SOURCES

libapplication_epidemic_la_LDFLAGS = -module
